### ISSUE TITLE
Core update?

### ISSUE THREAD

**Issue by ultimike** [phase2/openatrium-drops-7#10]
Hi @mike-potter - thanks for your continued willingness(?) to keep Open Atrium on D7 updated. I saw that you updated https://www.drupal.org/project/openatrium a few days ago, I'm curious when you think this project will be updated as well?

Do you have an amazon wish list I can access to sweeten the pot a bit? 😄 

thanks,  
-mike

**Comment by mike-potter** [comment]
Lol, I have a steam wishlist https://store.steampowered.com/wishlist/profiles/76561198042983624/#sort=order

But seriously, I hope to get to this on Monday.  It's been a crazy client week.

**Comment by mike-potter** [comment]
Done!  Thanks for the encouragement Michael!
